config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {registrations: 'user/registrations'} do
    get 'sign_out', to: 'devise/sessions#destroy'
  end

  resources :users do
      resources :user_emails, only: [:index, :create, :destroy]
      get '/user_emails/confirmation', to: "user_emails#confirmation", as: "email_confirmation"
  end

  namespace :api do
    namespace :v1 do
      resources :sites, only: [] do
        resources :folders do
          resources :pages, only: [:create, :update]
          resources :streams, only: [:create, :update]
          resources :template_cards, only: [:index, :show] do
            get "validate", on: :member
          end
          resources :datacasts, only: [:create, :update]
          resources :streams, only: [:create, :update]
          post "/streams/:id/publish", to: "streams#publish", as: :publish_stream
        end
        resources :verticals, only: [] do
          get "view_casts", on: :member
        end
      end

      # resources :folders, only: [] do
      #   resources :template_cards, only: [:index, :show] do
      #     get "validate", on: :member
      #   end
      #   resources :datacasts, only: [:create, :update]
      #   resources :streams, only: [:create, :update]
      #   post "/streams/:id/publish", to: "streams#publish", as: :publish_stream
      # end
      post "smartcrop", to: "utilities#smartcrop"
      get '/iframely', to: "utilities#iframely"
      get '/oembed', to: "utilities#oembed"
      resources :view_casts, only: [:show]
      resources :template_data, only: [:create]
    end
  end

  get ":site_id/apps", to: "template_apps#index", as: :apps_site
  get ":site_id/apps/d/:template_datum_id", to: "template_data#show", as: :site_template_datum
  get ":site_id/apps/d/:template_datum_id/:id", to: "template_fields#edit", as: :edit_site_template_datum_template_field

  resources :sites do
    post "fetch_new_data", on: :member
    #app store ---
    resources :template_apps, only: [:edit, :update]
    resources :site_template_apps, only: [:index, :destroy, :install] do
      post "invite", on: :member
      get "accept", on: :member
    end
    resources :template_data, only: [] do
      resources :template_fields do
        get "move_up", on: :member
        get "move_down", on: :member
      end
    end
    #app store ---

    resources :permissions do
      get "change_owner_role", on: :member
      put "change_role", on: :member
    end
    resources :permission_invites
    get "remove_favicon", "remove_logo", "integrations", on: :member
    resources :ref_categories do
      get 'landing_card', on: :member
      resources :feeds do
        post "force_fetch_feeds", on: :member
      end
      resources :feed_links do
        post "create_view_cast", on: :member
      end
      resources :site_vertical_navigations do
        put "move_up", "move_down", on: :member
      end
      put '/disable', to: "ref_categories#disable", on: :member
    end
    get "/sections", to: "ref_categories#sections", on: :member
    get "/intersections", to: "ref_categories#intersections", on: :member
    get "/sub_intersections", to: "ref_categories#sub_intersections", on: :member

    resources :folders do
      resources :stories, only: [:index]

      resources :view_casts
      resources :uploads, only: [:new, :create, :index]
    end
    resources :pages do
      put "remove_cover_image", on: :member
      get "distribute", on: :member
      get "ads", on: :member
      resources :ad_integrations, only: [:create, :destroy]
    end
    resources :stories, only: [:index] do
      get "edit/write", to: "stories#edit_write", on: :member
      get "edit/assemble", to: "stories#edit_assemble", on: :member
      get "edit/distribute", to: "stories#edit_distribute", on: :member
      get "edit/ads", to: "stories#edit_ads", on: :member
      post "import", to: "stories#import_story", on: :collection
    end
    resources :streams do
      post :publish, on: :member
      resources :stream_entities, only: [:create, :destroy] do
        put "move_up", "move_down", on: :member
      end
    end
    resources :page_streams, only: [:update]
    resources :images, only: [:index, :create, :show]
    resources :image_variations, only: [:create, :show] do
      post :download, on: :member
    end
  end

  scope :admin do
    resources "template_pages", only: [:index, :create, :update, :edit, :destroy]
  end


  root 'static_pages#index'
end

app/controllers/api/v1/template_data_controller.rb
class Api::V1::TemplateDataController < ApiController
    skip_before_action :set_user_from_token, :set_global_objects

    def create
        @template_datum, success = TemplateDatum.create_or_update(template_datum_params)
        if success
            render json: {key: "Schemas/#{@template_datum.name}/#{@template_datum.version}/",bucket: ENV["AWS_S3_BUCKET"], distribution_id: ENV["AWS_CDN_ID"]}, status: 200
        else
            render json: {error_message: "This version of #{@template_datum.name} is already published. Please publish a new version"}, status: 422
        end
    end

    private

    def template_datum_params
        params.require(:template_datum).permit(:name, :version, :change_log, :status)
    end

end

app/controllers/template_data_controller.rb
require 'json'

class TemplateDataController < ApplicationController
  
  def index
    @template_datums = @site.template_data.order("updated_at desc")
  end

  def show
    @template_datum = TemplateDatum.friendly.find(params[:template_datum_id])
    @template_fields = @template_datum.template_fields.order("sort_order")
    @json_schema = JSON.pretty_generate(@template_datum.get_schema_json)
  end
end

app/views/template_data/show.html.erb
<div style="margin-left: auto; margin-right: auto; width: 540px;">
    <p><%= link_to "Apps by #{@site.name}", apps_site_path(@site)%></p>
    <h1>
        <%= @template_datum.name %> 
        <% if !@template_datum.template_app.is_public %>
            <%= image_tag "lock.png", height: "15px;"%>
        <% end %>
        <span style="float: right;"><span class="badge badge-primary" style="background: #9D42A3; font-size: 12px;">Schema</span></span>
    </h1>
    <nav>
      <div class="nav nav-tabs" id="nav-tab" role="tablist">
        <a class="nav-item nav-link active" id="nav-home-tab" data-toggle="tab" href="#nav-home" role="tab" aria-controls="nav-home" aria-selected="true">Fields (<%= @template_datum.template_fields.count%>)</a>
        <a class="nav-item nav-link" id="nav-cards-tab" data-toggle="tab" href="#nav-cards" role="tab" aria-controls="nav-cards" aria-selected="false">Cards using this Schema (<%= @template_datum.template_cards.count%>)</a>
        <a class="nav-item nav-link" id="nav-profile-tab" data-toggle="tab" href="#nav-profile" role="tab" aria-controls="nav-profile" aria-selected="false">JSON</a>
      </div>
    </nav>
    <% if user_signed_in? and current_user.is_admin_from_pykih %>
        <div style="text-align: right;">
            <%= link_to "Edit", edit_site_template_app_path(@site, @template_datum.template_app) %>
        </div>
    <% end %>
    <br/>
    <% if @template_datum.template_app.blank? %>
        <p class="lead"><%= @template_datum.template_app.pitch %></p>
    <% end %>
    <div class="tab-content" id="nav-tabContent">
      <div class="tab-pane fade show active" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab">
          <br/>
          <table class="table ">  
          <tbody>
          <% @template_fields.each_with_index do |template_field, i| %>
            <tr>
              <td>
                  <% if template_field.data_type == "short_text" %>  
                      <%= image_tag "svg/short_text.svg", width: "24px", title: "Short Text" %>
                  <% elsif template_field.data_type == "long_text" %>
                      <%= image_tag "svg/long_text.svg", width: "24px", title: "Long Text" %>
                  <% elsif template_field.data_type == "integer" %>
                      <%= image_tag "svg/number.svg", width: "24px", title: "Integer" %>
                  <% elsif template_field.data_type == "decimal" %>
                      <%= image_tag "svg/number.svg", width: "24px", title: "Decimal" %>
                  <% elsif template_field.data_type == "boolean" %>
                      <%= image_tag "svg/boolean.svg", width: "24px", title: "Boolean" %>
                  <% elsif template_field.data_type == "temporal" %>
                      <%= image_tag "svg/datetime.svg", width: "24px", title: "Temporal" %>
                  <% else %>
                      <%= image_tag "svg/object.svg", width: "24px", title: "Object" %>
                  <% end %>
                  <!--<% %w(short_text long_text).include?(template_field.data_type) ? (template_field.data_type == "short_text" ? "Short Text" : "Long Text") : template_field.data_type.capitalize %>-->
                  &nbsp;&nbsp;&nbsp;&nbsp;
                  <%= link_to edit_site_template_datum_template_field_path(@site, @template_datum, template_field) do %>
                      <% if template_field.is_required %>
                          *
                      <% end %>
                      <%= template_field.name %>
                  <% end %>
                  <span class="gray small">(<%= template_field.key_name %>)</span>
              </td>
              <td>
                  <b><%= template_field.is_entry_title ? "Record title" : "" %></b>
              </td>
    
    
              <!--<td><%= template_field.inclusion_list.present? ? template_field.inclusion_list.join(",") : "" %></td>
              <td><%= template_field.inclusion_list_names.join(",") if template_field.inclusion_list_names.present? %></td>
              <td><%= %w(integer decimal).include?(template_field.data_type) ? template_field.min : "NA" %></td>
              <td><%= %w(integer decimal).include?(template_field.data_type) ? template_field.max : "NA" %></td>
              <td><%= %w(integer decimal).include?(template_field.data_type) ? template_field.multiple_of : "NA" %></td>
              <td><%= %w(integer decimal).include?(template_field.data_type) ? (template_field.ex_min ? "Yes" : "No") : "NA" %></td>
              <td><%= %w(integer decimal).include?(template_field.data_type) ? (template_field.ex_max ? "Yes" : "No") : "NA" %></td>

              <td><%= %w(short_text temporal).include?(template_field.data_type) ? template_field.format : "NA" %></td>
              <td><%= %w(short_text long_text temporal).include?(template_field.data_type) ? template_field.format_regex : "NA" %></td>
              <td><%= %w(short_text long_text temporal).include?(template_field.data_type) ? template_field.length_minimum : "NA" %></td>
              <td><%= %w(short_text long_text temporal).include?(template_field.data_type) ? template_field.length_maximum : "NA" %></td>-->  
            <% if user_signed_in? %>
                <td><%= link_to "&#8593;".html_safe, move_up_site_template_datum_template_field_path(@site, @template_datum, template_field) if i != 0 %></td>
                <td><%= link_to "&#8595;".html_safe, move_down_site_template_datum_template_field_path(@site, @template_datum, template_field) if i != @template_fields.count - 1 %></td>
                <td><%= link_to "x", site_template_datum_template_field_path(@site, @template_datum, template_field), method: :delete %></td>
            <% end %>
          </tr>
        <% end %>
        </tbody>
      </table></div>
      <div class="tab-pane fade" id="nav-cards" role="tabpanel" aria-labelledby="nav-cards-tab">
          <% @template_datum.template_cards.each do |card| %>
              <% app = card.template_app %>
              <%= render partial: "template_apps/row", locals: {app: app} %>
          <% end %>
      </div>
      <div class="tab-pane fade" id="nav-profile" role="tabpanel" aria-labelledby="nav-profile-tab">
          <br/>
          <%= image_tag("glyphicons-511-duplicate.png", class: "copy-to-clipboard") %>
          <pre id="json-schema"><%= @json_schema %></pre>
    </div>
    </div>
  </div>


  <br/><br/>
</div>


<script>
  $(document).ready(function(){
      
      // Javascript to enable link to tab
      var url = document.location.toString();
      if (url.match('#')) {
          $('.nav-tabs a[href="#' + url.split('#')[1] + '"]').tab('show');
      } 

      // Change hash for page-reload
      $('.nav-tabs a').on('shown.bs.tab', function (e) {
          window.location.hash = e.target.hash;
      })
      
    function copyToClipboard(containerid) {
      if (document.selection) {
        var range = document.body.createTextRange();
        range.moveToElementText(document.getElementById(containerid));
        range.select().createTextRange();
        document.execCommand("copy");
      } else if (window.getSelection) {
        var range = document.createRange();
        range.selectNode(document.getElementById(containerid));
        window.getSelection().addRange(range);
        document.execCommand("copy");
        alert("text copied");
      }
    }

    $(".copy-to-clipboard").click(function () {
      copyToClipboard("json-schema");
    });
  });
</script>

<style>
  .json-schema-container{
    background-color: #F2F2F2;
  }

  .copy-to-clipboard{
    float: right;
    width: 15px;
    display: block;
  }
</style>