config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {registrations: 'user/registrations'} do
    get 'sign_out', to: 'devise/sessions#destroy'
  end

  resources :users do
      resources :user_emails, only: [:index, :create, :destroy]
      get '/user_emails/confirmation', to: "user_emails#confirmation", as: "email_confirmation"
  end

  namespace :api do
    namespace :v1 do
      resources :sites, only: [] do
        resources :folders do
          resources :pages, only: [:create, :update]
          resources :streams, only: [:create, :update]
          resources :template_cards, only: [:index, :show] do
            get "validate", on: :member
          end
          resources :datacasts, only: [:create, :update]
          resources :streams, only: [:create, :update]
          post "/streams/:id/publish", to: "streams#publish", as: :publish_stream
        end
        resources :verticals, only: [] do
          get "view_casts", on: :member
        end
      end

      # resources :folders, only: [] do
      #   resources :template_cards, only: [:index, :show] do
      #     get "validate", on: :member
      #   end
      #   resources :datacasts, only: [:create, :update]
      #   resources :streams, only: [:create, :update]
      #   post "/streams/:id/publish", to: "streams#publish", as: :publish_stream
      # end
      post "smartcrop", to: "utilities#smartcrop"
      get '/iframely', to: "utilities#iframely"
      get '/oembed', to: "utilities#oembed"
      resources :view_casts, only: [:show]
      resources :template_data, only: [:create]
    end
  end

  get ":site_id/apps", to: "template_apps#index", as: :apps_site
  get ":site_id/apps/d/:template_datum_id", to: "template_data#show", as: :site_template_datum
  get ":site_id/apps/d/:template_datum_id/:id", to: "template_fields#edit", as: :edit_site_template_datum_template_field

  resources :sites do
    post "fetch_new_data", on: :member
    #app store ---
    resources :template_apps, only: [:edit, :update]
    resources :site_template_apps, only: [:index, :destroy, :install] do
      post "invite", on: :member
      get "accept", on: :member
    end
    resources :template_data, only: [] do
      resources :template_fields do
        get "move_up", on: :member
        get "move_down", on: :member
      end
    end
    #app store ---

    resources :permissions do
      get "change_owner_role", on: :member
      put "change_role", on: :member
    end
    resources :permission_invites
    get "remove_favicon", "remove_logo", "integrations", on: :member
    resources :ref_categories do
      get 'landing_card', on: :member
      resources :feeds do
        post "force_fetch_feeds", on: :member
      end
      resources :feed_links do
        post "create_view_cast", on: :member
      end
      resources :site_vertical_navigations do
        put "move_up", "move_down", on: :member
      end
      put '/disable', to: "ref_categories#disable", on: :member
    end
    get "/sections", to: "ref_categories#sections", on: :member
    get "/intersections", to: "ref_categories#intersections", on: :member
    get "/sub_intersections", to: "ref_categories#sub_intersections", on: :member

    resources :folders do
      resources :stories, only: [:index]

      resources :view_casts
      resources :uploads, only: [:new, :create, :index]
    end
    resources :pages do
      put "remove_cover_image", on: :member
      get "distribute", on: :member
      get "ads", on: :member
      resources :ad_integrations, only: [:create, :destroy]
    end
    resources :stories, only: [:index] do
      get "edit/write", to: "stories#edit_write", on: :member
      get "edit/assemble", to: "stories#edit_assemble", on: :member
      get "edit/distribute", to: "stories#edit_distribute", on: :member
      get "edit/ads", to: "stories#edit_ads", on: :member
      post "import", to: "stories#import_story", on: :collection
    end
    resources :streams do
      post :publish, on: :member
      resources :stream_entities, only: [:create, :destroy] do
        put "move_up", "move_down", on: :member
      end
    end
    resources :page_streams, only: [:update]
    resources :images, only: [:index, :create, :show]
    resources :image_variations, only: [:create, :show] do
      post :download, on: :member
    end
  end

  scope :admin do
    resources "template_pages", only: [:index, :create, :update, :edit, :destroy]
  end


  root 'static_pages#index'
end

app/models/permission_invite.rb
# == Schema Information
#
# Table name: permission_invites
#
#  id                :integer          not null, primary key
#  permissible_id    :integer
#  email             :string(255)
#  ref_role_slug     :string(255)
#  created_by        :integer
#  updated_by        :integer
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  permissible_type  :string(255)
#  name              :string(255)
#  create_user       :boolean
#  do_not_email_user :boolean
#

class PermissionInvite < ApplicationRecord

    #CONSTANTS
    #CUSTOM TABLES
    #GEMS
    #CONCERNS
    include Propagatable
    include AssociableBy
    #ASSOCIATIONS
    belongs_to :permissible, polymorphic: true

    #ACCESSOR
    attr_accessor :redirect_url
    #VALIDATIONS
    validates :permissible_type, presence: true
    validates :permissible_id, presence: true
    validates :email, presence: true, format: { with: /\A[^@\s]+@([^@.\s]+\.)+[^@.\s]+\z/ }
    validates :ref_role_slug, presence: true
    validate  :is_unique_row?, on: :create

    #CALLBACKS
    before_create :before_create_set
    #SCOPE
    scope :site_permissions, -> { where(permissible_type: "Site") }
    #OTHER
    #PRIVATE
    private

    def is_unique_row?
        errors.add(:email, "already invited.") if PermissionInvite.where(permissible_type: self.permissible_type, permissible_id: self.permissible_id, email: self.email).first.present?
        true
    end

    def before_create_set
        self.email = self.email.downcase
    end

end

app/controllers/permission_invites_controller.rb
class PermissionInvitesController < ApplicationController

  before_action :authenticate_user!, :sudo_role_can_add_site_people
  before_action :set_permission_invite, only: [:show, :edit, :update, :destroy]

  def index
    @permissions = @site.permissions.not_hidden.includes(:user).page params[:page]
    @permission_invite = PermissionInvite.new
    @permission_invites = @site.permission_invites
    @pending_invites_count = @site.permission_invites.count
    @people_count = @site.permissions.not_hidden.count
    @permission_roles = PermissionRole.where.not(slug: "owner").pluck(:name, :slug)
    @is_admin = true
    
  end

  def create
    @permission_invite = PermissionInvite.new(permission_invite_params)
    per = UserEmail.find_by(email: @permission_invite.email)
    user = per.present? ? per.user : nil
    if user.present?
      a = user.create_permission(permission_invite_params[:permissible_type], permission_invite_params[:permissible_id], @permission_invite.ref_role_slug)
      if a.id.present?
        redirect_to permission_invite_params[:redirect_url], notice: t("permission_invite.add")
      else
        a.errors.each do |key, value|
          @permission_invite.errors.add(:email, value)
        end
        @permissions = @site.permissions.not_hidden.includes(:user).page params[:page]
        @permission_invites = @site.permission_invites
        @people_count = @site.permissions.not_hidden.count
        @pending_invites_count = @site.permission_invites.count
        @permission_invites = @site.permission_invites
        @permission_roles = PermissionRole.where.not(slug: "owner").pluck(:name, :slug)
        @show_modal = true
        render "permission_invites/index"
      end
    else
      if @permission_invite.save
        notice = t("permission_invite.invite")
        if @permission_invite.create_user
          new_user = User.new({email: @permission_invite.email,name: @permission_invite.name })
          pass = SecureRandom.hex(10)
          new_user.password = pass
          new_user.password_confirmation = pass
          new_user.skip_confirmation! if @permission_invite.do_not_email_user
          new_user.save
          Permission.create(name: @permission_invite.name, user_id: new_user.id, permissible_type: @permission_invite.permissible_type, permissible_id: @permission_invite.permissible_id, created_by: @permission_invite.created_by, updated_by: @permission_invite.updated_by, ref_role_slug: @permission_invite.ref_role_slug)
          @permission_invite.destroy
        end
        unless @permission_invite.do_not_email_user
          PermissionInvites.invite(@permission_invite.name, @site, @permission_invite.email).deliver
        else
          if @permission_invite.create_user
            notice = t("permission_invite.noinvite")
          else
            notice = t("permission_invite.nouser_noinvite")
          end
        end
        redirect_to permission_invite_params[:redirect_url], notice: notice
      else
        @permissions = @site.permissions.includes(:user).page params[:page]
        @permission_invites = @site.permission_invites
        @people_count = @site.users.count
        @pending_invites_count = @site.permission_invites.count
        @permission_invites = @site.permission_invites
        @show_modal = true
        render "permission_invites/index"
      end
    end
  end

  def destroy
    @permission_invite.destroy
    redirect_to params[:redirect_url], notice: t("permission_invite.removed")
  end

  private

    def set_permission_invite
      @permission_invite = PermissionInvite.find(params[:id])
    end

    def permission_invite_params
      params.require(:permission_invite).permit(:email, :ref_role_slug, :created_by, :name, :create_user, :do_not_email_user, :updated_by, :permissible_type, :permissible_id, :redirect_url)
    end
end

app/views/permission_invites/index.html.erb
<h1>Adminland</h1>
<%= render partial: "sites/header" %>
<div style="margin-left: auto; margin-right: auto; width: 540px;">
    <%= simple_form_for [@site, @permission_invite] do |f| %>
        <% if @permission_invite.errors.any? %>
            <div id="error_explanation" class="ui error message">
                <div class="header">
                    <%= pluralize(@permission_invite.errors.count, "error") %> prohibited this permission_invite from being saved:
                </div>
                <% @permission_invite.errors.full_messages.each do |message| %>
                    <p>
                        <%= message %>
                    </p>
                <% end %>
            </div>
        <% end %>
        <%= f.hidden_field :permissible_type, value: "Site" %>
        <%= f.hidden_field :permissible_id, value: @site.id %>
        <%= f.hidden_field :created_by, value: current_user.id %>
        <%= f.hidden_field :updated_by, value: current_user.id %>
        <%= f.input :name, required: true, autofocus: true %>
        <%= f.input :email, as: :email, id: :permission_invite_email, required: true, hint: "Ensure this email really belongs to the author. If you use someone else's email ID, and that person is on ProtoTYPE then they will get access to the account." %>
        <%= f.hidden_field :redirect_url, value: site_permission_invites_path(@site) %>
        <%= f.hidden_field :ref_role_slug, value: "editor" %>
        <!-- #collection: @permission_roles, include_blank: false, label: "Role"-->
        <%= f.input :create_user, as: :boolean, label: "&nbsp; Go ahead and create user?".html_safe, hint: "We will assign a random secure password." %>
        <%= f.input :do_not_email_user, as: :boolean, label: "&nbsp; Do not email this user".html_safe, hint: "Use this if writer will send you the article over email and you will file it." %>
        <%= f.submit "Invite" %>
    <% end %>
    <br/><br/>
    <h2>Team</h2>
    <br/>
    <% if @permissions.first.blank? %>
        <p class="hint">No team members invited yet.</p>
    <% else %>
        <table class="table table-hover">
            <tbody>
                <% @permissions.each do |permission| %>
                    <tr>
                        <td style="width: 25px; border: 0px;"><img class="rounded" src=<%=avatar_url(permission.user.email)%>>
                        </td>
                        <td style="border: 0px;">
                            <%= permission.name %>
                            <% if permission.status == "Deactivated" %>
                                <i style="font-weight: 200; color: gray;">(Deactivated)</i>
                            <% end %>
                            <br/>
                            <div class="hint"><%= permission.user.email %></div>
                            <% if permission.user.current_sign_in_at.present? %>
                                <div class="hint">Last seen <%= time_ago_in_words(permission.user.current_sign_in_at) %> ago.</div>
                            <% end %>
                        </td>
                        <td style="border: 0px;" class="hint">
                            <%= permission.bio %>
                        </td>
                        <td style="border: 0px; width: 70px;">
                            <%= link_to "Edit", edit_site_permission_path(@site, permission) %>
                        </td>
                        <!--
                        <td style="border: 0px; width: 100px;">
                            <% simple_form_for(permission, url: change_role_site_permission_path(@site, permission), class: "permission_forms", method: :put) do |f| %>
                                <%= f.hidden_field :updated_by, value: current_user.id %>
                                <%= f.hidden_field :redirect_url, value: site_permission_invites_path(@site) %>
                                <%= f.input :ref_role_slug, collection: @permission_roles, include_blank: false, label: false, input_html: {class: "permission_select"} %>
                            <% end %>
                        </td>-->
                        <td style="border: 0px;">
                            <% if current_user.id != permission.user_id and permission.status != "Deactivated" %>
                                <%= link_to "x", site_permission_path(@site,   permission, redirect_url: site_permission_invites_path(@site)), method: :delete, data: { confirm: 'Are you sure?' } %>
                            <% end %>
                        </td>
                    </tr>
                <% end %>
                <%= paginate @permissions, theme: 'twitter-bootstrap-4', pagination_class: "pagination-sm" %>
            </tbody>
        </table>
    <% end %>
    <% if @pending_invites_count != 0 %>
        <br/><br/>
        <h2>Pending Invites</h2>
        <br/>
        <table class="table">
            <tbody>
                <% @permission_invites.each do |permission_invite| %>
                    <tr>
                        <td style="width: 25px; border: 0px;"><img class="rounded" src=<%=avatar_url(permission_invite.email)%>>
                        </td>
                        <td style="border: 0px;">
                            <%= permission_invite.email %>
                                <div class="hint">Invited by
                                    <%= permission_invite.creator.name %>
                                        <%= time_ago_in_words (permission_invite.created_at) %>.
                                </div>
                        </td>
                        <td style="border: 0px;">
                            <%= link_to "x", site_permission_invite_path(@site, permission_invite,redirect_url: site_permission_invites_path(@site)), method: :delete, data: { confirm: 'Are you sure?' } %>
                        </td>
                    </tr>
                <% end %>
            </tbody>
        </table>
    <% end %>
</div>

<script type="text/javascript">
    $(document).on("turbolinks:load", function(){
        $(".permission_select").on("change", function(){
            $(this).parents('form').submit();
        });
    });
</script>

app/views/permission_invites/invite.html.erb
Hello <%= @user %>,<br/>
===============================================
<br/>
<br/>
You have been invited to participate in <%= @site.name %>
<br/>
Sign up with PROTO at
<%= new_user_registration_url %>