config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {registrations: 'user/registrations'} do
    get 'sign_out', to: 'devise/sessions#destroy'
  end

  resources :users do
      resources :user_emails, only: [:index, :create, :destroy]
      get '/user_emails/confirmation', to: "user_emails#confirmation", as: "email_confirmation"
  end

  namespace :api do
    namespace :v1 do
      resources :sites, only: [] do
        resources :folders do
          resources :pages, only: [:create, :update]
          resources :streams, only: [:create, :update]
          resources :template_cards, only: [:index, :show] do
            get "validate", on: :member
          end
          resources :datacasts, only: [:create, :update]
          resources :streams, only: [:create, :update]
          post "/streams/:id/publish", to: "streams#publish", as: :publish_stream
        end
        resources :verticals, only: [] do
          get "view_casts", on: :member
        end
      end

      # resources :folders, only: [] do
      #   resources :template_cards, only: [:index, :show] do
      #     get "validate", on: :member
      #   end
      #   resources :datacasts, only: [:create, :update]
      #   resources :streams, only: [:create, :update]
      #   post "/streams/:id/publish", to: "streams#publish", as: :publish_stream
      # end
      post "smartcrop", to: "utilities#smartcrop"
      get '/iframely', to: "utilities#iframely"
      get '/oembed', to: "utilities#oembed"
      resources :view_casts, only: [:show]
      resources :template_data, only: [:create]
    end
  end

  get ":site_id/apps", to: "template_apps#index", as: :apps_site
  get ":site_id/apps/d/:template_datum_id", to: "template_data#show", as: :site_template_datum
  get ":site_id/apps/d/:template_datum_id/:id", to: "template_fields#edit", as: :edit_site_template_datum_template_field

  resources :sites do
    post "fetch_new_data", on: :member
    #app store ---
    resources :template_apps, only: [:edit, :update]
    resources :site_template_apps, only: [:index, :destroy, :install] do
      post "invite", on: :member
      get "accept", on: :member
    end
    resources :template_data, only: [] do
      resources :template_fields do
        get "move_up", on: :member
        get "move_down", on: :member
      end
    end
    #app store ---

    resources :permissions do
      get "change_owner_role", on: :member
      put "change_role", on: :member
    end
    resources :permission_invites
    get "remove_favicon", "remove_logo", "integrations", on: :member
    resources :ref_categories do
      get 'landing_card', on: :member
      resources :feeds do
        post "force_fetch_feeds", on: :member
      end
      resources :feed_links do
        post "create_view_cast", on: :member
      end
      resources :site_vertical_navigations do
        put "move_up", "move_down", on: :member
      end
      put '/disable', to: "ref_categories#disable", on: :member
    end
    get "/sections", to: "ref_categories#sections", on: :member
    get "/intersections", to: "ref_categories#intersections", on: :member
    get "/sub_intersections", to: "ref_categories#sub_intersections", on: :member

    resources :folders do
      resources :stories, only: [:index]

      resources :view_casts
      resources :uploads, only: [:new, :create, :index]
    end
    resources :pages do
      put "remove_cover_image", on: :member
      get "distribute", on: :member
      get "ads", on: :member
      resources :ad_integrations, only: [:create, :destroy]
    end
    resources :stories, only: [:index] do
      get "edit/write", to: "stories#edit_write", on: :member
      get "edit/assemble", to: "stories#edit_assemble", on: :member
      get "edit/distribute", to: "stories#edit_distribute", on: :member
      get "edit/ads", to: "stories#edit_ads", on: :member
      post "import", to: "stories#import_story", on: :collection
    end
    resources :streams do
      post :publish, on: :member
      resources :stream_entities, only: [:create, :destroy] do
        put "move_up", "move_down", on: :member
      end
    end
    resources :page_streams, only: [:update]
    resources :images, only: [:index, :create, :show]
    resources :image_variations, only: [:create, :show] do
      post :download, on: :member
    end
  end

  scope :admin do
    resources "template_pages", only: [:index, :create, :update, :edit, :destroy]
  end


  root 'static_pages#index'
end

app/controllers/stories_controller.rb
require 'json'
require 'net/http'
require 'open-uri'

class StoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_page, only: [:edit_write, :edit_assemble, :edit_distribute, :edit_ads]
  before_action :sudo_can_see_all_pages, only: [:edit_write, :edit_write, :edit_assemble, :edit_distribute, :edit_ads]

  def index
    if params[:page].present? and params[:page].class != String
      p_params = page_params
      @page = Page.new(p_params)
      if p_params["ref_category_series_id"].blank?
        redirect_to site_stories_path(@site, folder_id: @page.folder_id), alert: 'You must associate a vertical with workspace'
      else
        if p_params.has_key?('cover_image_attributes') and !p_params['cover_image_attributes'].has_key?("image")
          p_params.delete('cover_image_attributes')
        end
        @page.headline = @page.one_line_concept
        @page.english_headline = @page.one_line_concept unless @site.is_english
        @page.created_by = current_user.id
        @page.updated_by = current_user.id
        @page.collaborator_lists = ["#{current_user.id}"] if ["contributor", "writer"].include?(@permission_role.slug)
        if @page.save
          redirect_to site_stories_path(@site, folder_id: @page.folder_id), notice: 'Page was successfully created.'
        else
          flash.now.alert = @page.errors.full_messages
          redirect_to site_stories_path(@site, folder_id: @page.folder_id), alert: 'Error creating page'
        end
      end
    else
      if @permission_role.can_see_all_pages
        z = @folder.pages.where(template_page_id: TemplatePage.where.not(name: "Homepage: Vertical").pluck(:id).uniq)
      else
        z = current_user.pages(@folder).where(template_page_id: TemplatePage.not(name: "Homepage: Vertical").pluck(:id).uniq)
      end
      @bylines = Permission.where(id: z.pluck(:byline_id).uniq).order(:name)
      @q = z.search(params[:q])
      @pages = @q.result.page(params[:page]).per(15)
      @page = Page.new
      @ref_intersection = RefCategory.where(site_id: @site.id, genre: "intersection", is_disabled: [false, nil]).order(:name).map {|r| ["#{r.name}", r.id]}
      @ref_intersections = RefCategory.where(site_id: @site.id, genre: "intersection", is_disabled: [false, nil]).order(:name)
      @ref_sub_intersection = RefCategory.where(site_id: @site.id, genre: "sub intersection", is_disabled: [false, nil]).order(:name).map {|r| ["#{r.name}", r.id]}
      @ref_sub_intersections = RefCategory.where(site_id: @site.id, genre: "sub intersection", is_disabled: [false, nil]).order(:name)
      @article = TemplatePage.where(name: "article").first
      @article_or_compendium = TemplatePage.where(name: ['article', 'compendium']).pluck(:name, :id).map{|d| [d[0].titleize, d[1]]}
    end
  end

  def edit_assemble
    @view_cast = @page.view_cast if @page.view_cast_id.present?
    @page_streams = @page.page_streams
    @page.publish = @page.status == 'published'
    @is_article_page = @page.template_page.name == "article"
    @page_stream_narrative = @page.streams.where(title: "#{@page.id.to_s}_Story_Narrative").first
    @page_stream_related = @page.streams.where(title: "#{@page.id.to_s}_Story_Related").first
    @page_stream_related7c = @page_stream_related.page_streams.first
    @page_stream_narrative7c = @page_stream_narrative.page_streams.first
    exclude_view_casts = StreamEntity.view_casts.where(stream_id: [@page_stream_narrative.id, @page_stream_related.id]).pluck(:entity_value)
    @all_cards = @site.view_casts.where.not(id: exclude_view_casts).where(is_autogenerated: false, template_card_id: TemplateCard.where.not(name: ['toParagraph', "Oxfam IRBF: toCompanyProfile", "Oxfam IRBF: toQuestion", "Oxfam IRBF: toSurveyScores","toData: Rating with drill down", "toData: IRBF Grid", "toData: IRBF Tooltip"])).where(folder_id: @site.folders.active.where(ref_category_vertical_id: @page.series.id).pluck(:id)).order([updated_at: :desc, created_at: :desc])
    @all_cards += @site.view_casts.where.not(id: exclude_view_casts).where(template_card_id: TemplateCard.where(name: "toStory")).where(is_autogenerated: true).where(folder_id: @site.folders.active.where(ref_category_vertical_id: @page.series.id).pluck(:id)).order([updated_at: :desc, created_at: :desc])
    if @page.template_page.name == "Homepage: Vertical"
      title = "#{@page.id.to_s}_Section_16c_Hero"
    elsif @page.template_page.name == "article" or @page.template_page.name == "compendium"
      title = "#{@page.id.to_s}_Story_16c_Hero"
    else
      title = "#{@page.id.to_s}_Data_16c_Hero"
    end
    @page_stream_16 = @page.streams.where(title: title).first
    @page_streamH16 = @page.page_streams.where(name_of_stream: "Hero").first
    @stream_entity = StreamEntity.new
  end

  def edit_write
    #- Seamless writing experience that gets converted into many Compose Cards
    #- Rao's app / Medium / Google Doc
    #@ref_intersection = RefCategory.where(site_id: @site.id, genre: "intersection", is_disabled: [false, nil]).order(:name).map {|r| ["#{r.name}", r.id]}
    #@ref_sub_intersection = RefCategory.where(site_id: @site.id, genre: "sub intersection", is_disabled: [false, nil]).order(:name).map {|r| ["#{r.name}", r.id]}
    @template_cards = @site.template_cards.where(is_current_version: true)

  end

  def edit_distribute
    #  cover_image_url_facebook         :text(65535)
    #  cover_image_url_square           :text(65535)
    # - Tags []
    # - Related to Geography?
    #     > Country
    #     > State
    #     > District
    #     > Location
    @cover_image_alignment = [["Horizontal", "horizontal"], ["Vertical", "vertical"]]
    @ref_category_intersection = @site.ref_categories.where(genre: "intersection").map {|i| [i.name, i.id]}
    @ref_category_sub_intersection = @site.ref_categories.where(genre: "sub intersection").map {|i| [i.name, i.id]}
    @image = @page.cover_image
    if @image.blank?
        @page.build_cover_image
    end
    #  cover_image_id_7_column          :integer
    #  cover_image_id_4_column
    #  cover_image_id_3_column
    #  cover_image_id_2_column
    #  cover_image_credit


  end

  def edit_ads
    @ad_integrations = @page.ad_integrations
    @page_streams = @page.page_streams
    @ad_integration = AdIntegration.new
  end

  def import_story
    p_params = page_params
    @page = Page.new(p_params)
    @page.created_by = current_user.id
    @page.updated_by = current_user.id
    @page.headline = "Headline"
    # @page.html_key = "default_html_key"
    @page.published_at = DateTime.now
    if @page.save!
      redirect_to site_stories_path(@site, folder_id: @page.folder_id), notice: "Story will be imported shortly"
    else
      redirect_to site_stories_path(@site, folder_id: @page.folder_id), alert: "Error importing story"
    end
  end


  private

    def set_page
      @page = Page.friendly.find(params[:id])
    end

    def page_params
      params.require(:page).permit(:id, :site_id, :folder_id, :import_url, :headline, :meta_keywords, :meta_description, :summary, :template_page_id, :byline_id, :one_line_concept,
                                   :cover_image_url, :cover_image_url_7_column, :cover_image_url_facebook, :cover_image_url_square, :cover_image_alignment, :content,
                                   :is_sponsored, :is_interactive, :has_data, :has_image_other_than_cover, :has_audio, :has_video, :status, :published_at, :url,
                                   :ref_category_series_id, :ref_category_intersection_id, :ref_category_sub_intersection_id, :view_cast_id, :page_object_url, :created_by,:html_key,
                                   :updated_by, :english_headline, :due, :description, :cover_image_id_4_column, :cover_image_id_3_column, :cover_image_id_2_column, :cover_image_credit, :share_text_facebook,
                                     :share_text_twitter, :publish, :prepare_cards_for_assembling, :format, :importance,:external_identifier, collaborator_lists: [], cover_image_attributes: [:image, :site_id,:is_cover, :created_by,
                                     :updated_by])
    end
end

app/views/stories/_new.html.erb
<div>
    <div class="dropdown" style="display: inline;">
        <button class="btn btn-sm btn-dark dropdown-toggle" type="button" id="dropdownMenu2">
          + Quick add a story idea
        </button>
        <div class="dropdown-menu dropdown-menu-card dropdown-menu-right quick-pitch-story-card" style="right: 0; left: auto; width: 600px;">
            <div style="padding: 20px;">
                    <%= simple_form_for [@site, @page] do |f| %>
                        <%= f.error_notification %>
                        <div class="form-inputs">
                            <%= f.hidden_field :ref_category_series_id, value: @folder.ref_category_vertical_id %>
                            <%= f.hidden_field :site_id, value: @site.id %>
                            <%= f.hidden_field :folder_id, value: @folder.id %>
                            <div class="row">
                                <div class="col-xs-8">
                                    <% if @ref_intersection.first.present? %>
                                        <%= f.input :ref_category_intersection_id, label: "Intersection", collection: @ref_intersection, include_blank: true, input_html: {style: "width: 100%;", class: "selectpicker"} %>
                                    <% end %>
                                </div>
                                <div class="col-xs-8">
                                    <% if @ref_sub_intersection.first.present? %>
                                        <%= f.input :ref_category_sub_intersection_id, label: "Trend", collection: @ref_sub_intersection, include_blank: true, input_html: {style: "width: 100%;"} %>
                                    <% end %>
                                </div>
                            </div>
                            <% if @site.name == 'Oxfam India' and @folder.vertical.name == 'GlobalGoals' %>
                                <div class='row'>
                                    <div class="col-xs-8">
                                        <%= f.input :template_page_id, collection: @article_or_compendium, include_blank: false, label: "Use this as:", label_html: {style: "width: 100%; justify-content: left;"}, input_html: {style: "width: 100%;"}    %>
                                    </div>
                                </div>
                            <% else %>
                                <%= f.hidden_field :template_page_id, value: @article.id %>
                            <% end %>
                            <br/>
                            <%= f.input :one_line_concept, required: true, placeholder: "*Story pitch in at max 90 chars", minlength: 11 , maxlength: 90, label: false, input_html: {style: "width: 100%;"} %>
                            <br/>
                            <%= f.input :byline_id, collection: @site.all_members, required: true, label: "Byline Stream", input_html: {style: "width: 100%;"} %>
                            <br/>
                            <label class='control-label date optional' style="justify-content: left;">What do you want in this story?</label>
                            <div class="row">
                                <div class="col-sm-3">
                                    <%= f.input :has_image_other_than_cover, label: "&nbsp; #{image_tag "glyphicons-139-picture.png", height: 17}".html_safe %>
                                </div>
                                <div class="col-sm-3">
                                    <%= f.input :has_audio, label: "&nbsp; #{image_tag "glyphicons-301-microphone.png", height: 17}".html_safe %>
                                </div>
                                <div class="col-sm-3">
                                    <%= f.input :has_video, label: "&nbsp; #{image_tag "glyphicons-181-facetime-video.png", height: 16}".html_safe %>
                                </div>
                                <div class="col-sm-2">
                                    <%= f.input :has_data, label: "&nbsp; #{image_tag "glyphicons-43-pie-chart.png", height: 17}".html_safe %>
                                </div>
                                <div class="col-sm-4">
                                    <%= f.input :is_sponsored, label: "&nbsp; Sponsored?".html_safe %>
                                </div>
                            </div>
                            <br/>
                            <div class="row">
                                <div class="col-sm-8">
                                    <%= f.input :due, as: :date, label: "ETA:", label_html: {style: "width: 100%; justify-content: left;"} %>
                                </div>
                                <div class="col-sm-8">
                                    <%= f.input :published_at, as: :date, label: "Planned publish date:", label_html: {style: "width: 100%; justify-content: left;"} %>
                                </div>
                            </div>

                            <br/>
                            <div class="form-actions">
                              <%= f.button :submit, "Add" %>
                            </div>
                        </div>
                    <% end %>

                    </div>
        </div>
    </div>
    <div class="dropdown" style="display: inline;">
        <button class="btn btn-sm btn-dark dropdown-toggle" type="button" id="dropdownMenu3">
      + Import a story
        </button>
        <div class="dropdown-menu dropdown-menu-card dropdown-menu-right import-story-card" style="right: 0; left: auto; width: 600px;">
            <div style="padding: 20px; font-size: 1rem;">
                <%= simple_form_for @page, url: import_site_stories_path, method: :post  do |f| %>
                  <%= f.error_notification %>
                  <div class="form-inputs">
                    <%= f.hidden_field :ref_category_series_id, value: @folder.ref_category_vertical_id %>
                    <%= f.hidden_field :site_id, value: @site.id %>
                    <%= f.hidden_field :folder_id, value: @folder.id %>
                    <%= f.hidden_field :template_page_id, value: @article.id %>
                    <div class="row">
                      <div class="col-xs-16">
                        <%= f.input :import_url, label: "Paste URL of an article here", input_html: {style: "width: 100%;"}%>
                      </div>
                    </div>
                    <br/>
                    <div class="form-actions">
                      <%= f.button :submit, "Import" %>
                    </div>
                  </div>
                <% end %>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    $('#dropdownMenu2').on('click', function(event) {
        $('.quick-pitch-story-card').css('display', 'block')
        $('.import-story-card').css('display', 'none');
        event.stopPropagation();
    });

    $('#dropdownMenu3').on('click', function(event) {
        $('.import-story-card').css('display', 'block')
        $('.quick-pitch-story-card').css('display', 'none');
        event.stopPropagation();
    });
    $(document).click(function(e) {
        if (!$(e.target).is('.dropdown-menu-card, .dropdown-menu-card *')) {
            $(".dropdown-menu-card").css('display', 'none')
        }
    });
</script>

app/views/stories/_stories_header.html.erb
<%= stylesheet_link_tag "stories" %>
<%= javascript_include_tag "stories",'data-turbolinks-track': 'reload' %>
<p><%= link_to "< " + folder_name_(@folder), site_stories_path(@site, folder_id: @folder.id), "data-turbolinks"=> false %></p>
<h1><%= @page.headline %></h1>
<div class="protograph-page-tabs">
    <% if ["article", 'compendium'].include?(@page.template_page.name) %>
        <div class="<%= action_name != 'edit_write' ? "single-tab" : "single-tab active-tab" %>">
            <%= link_to "Write", edit_write_site_story_path(@site, @page, folder_id: @page.folder_id), "data-turbolinks" => "false" %>
        </div>
        <div class="<%= action_name != 'edit_assemble' ? "single-tab" : "single-tab active-tab" %>">
            <%= link_to "Layout", edit_assemble_site_story_path(@site, @page, folder_id: @page.folder_id), "data-turbolinks" => "false" %>
        </div>
    <% end %>
    <div class="<%= action_name != 'edit_distribute' ? "single-tab" : "single-tab active-tab" %>">
        <%= link_to "Package", edit_distribute_site_story_path(@site, @page, folder_id: @page.folder_id), "data-turbolinks" => "false" %>
    </div>
    <% if @page.status != 'draft' %>
        <div class="single-tab">
          <%= link_to "Go to page", @page.html_url, target: "_blank" %>
         </div>
    <% end %>
</div>

app/views/stories/edit_ads.html.erb
<%= render partial: "stories/stories_header" %>
<div class="row">
    <div style="margin-left: auto; margin-right: auto; width: 540px;">
        <div style="margin-left: auto; margin-right: auto; width: 540px;">
            <h3>Manage all the ads for each stream here:</h3>
            <% if @ad_integrations.count > 0 %>
                <table  class="table">
                    <% @ad_integrations.each do |ad|%>
                        <tr>
                            <td>
                                <%= ad.slot_text %>
                                <br/>
                                <p class='hint'><%= ad.page_stream.name_of_stream %> - <%= ad.sort_order %></p>
                            </td>
                            <td>
                                <%= link_to "x", [@site, @page, ad], method: :delete, data: { confirm: 'Are you sure?' } %>
                            </td>
                        </tr>
                    <% end %>
                </table>
            <% else %>
                <h4>There is no ad added on this story.</h4>
            <% end %>
        </div>
        <%= simple_form_for([@site, @page, @ad_integration]) do |f|%>
            <%= f.input :slot_text, as: :string, label: "Slot text", required: true %>
            <%= f.input :page_stream_id, collection: @page_streams.map{|p| [p.name_of_stream, p.id]}, include_blank: false %>
            <%= f.input :site_id, as: :hidden, input_html: {value: @site.id} %>
            <%= f.input :page_id, as: :hidden, input_html: {value: @page.id} %>
            <%= f.input :sort_order, required: true, label: "Position", input_html: { min: '0'} %>
            <%= f.input :div_id, required: true %>
            <%= f.input :width, required: true, input_html: { min: '0'} %>
            <%= f.input :height, required: true, input_html: { min: '0'} %>
            <%= f.button :submit, "Add" %>
        <% end %>
    </div>
</div>

app/views/stories/index.html.erb
<h1>
    <%= link_to folder_name_(@folder), site_stories_path(@site, folder_id: @folder.id), "data-turbolinks"=> false %>
    <% if !@folder.is_trash %>
        <span class="small thin"><%= link_to "Edit this workspace", edit_site_folder_path(@site, @folder) %></span>
    <% end %>
    <% if !@folder.is_trash %>
        <span style="float: right;">
            <form class="form-inline my-2 my-lg-0"><li style="list-style-type: none;"><%= render partial: "stories/new" %></li></form>
        </span>
    <% end %>
</h1>
<br/>
<div class="row">
    <div class="col-sm-12">
            <div class="protograph-page-tabs">
                <div class="single-tab">
                    <%= link_to "Cards", site_folder_view_casts_path(@site, @folder), "data-turbolinks" => "false" %>
                </div>
                <% if @folder.is_for_stories %>
                  <% if @folder.vertical.present? %>
                    <div class="single-tab active-tab">
                        <%= link_to "Stories", site_stories_path(@site,folder_id: @folder.id), "data-turbolinks" => "false" %>
                    </div>
                  <% end %>
                <% end %>
            </div>

            <% if @pages.first.blank? %>
                <div class="col-sm-16">
                    <div class="blankslate blankslate-spacious">
                        <% if @folder.is_trash %>
                            <h3>There are no stories in the recycle bin.</h3>
                        <% else %>
                            <h3>No stories created yet.</h3>
                            <p>Use the [+ Add a story] button on the top right or <%= link_to "Reset", site_folder_stories_path(@site, @folder) %>.</p>
                        <% end %>
                    </div>
                </div>
            <% else %>
                <table class="table">
                    <thead>
                        <tr>
                            <th style="border: 0px;"><%= sort_link(@q, :view_cast_id, '#') %>
                            </th>
                            <th style="border: 0px;">Editorial
                            </th>
                            <th style="border: 0px;">
                            </th>
                            <th style="border: 0px;">Headline
                            </th>
                            <th style="border: 0px;">Byline
                            </th>
                            <th style="border: 0px;"><%= sort_link(@q, :published_at) %>
                            </th>
                            <th style="border: 0px;"><%= sort_link(@q, :updated_at) %>
                            </th>
                        </tr>
                    </thead>

                    <% @pages.each do |d| %>
                        <tbody>

                                <tr>
                                    <td class="hint">
                                        <% if d.view_cast.present? %>
                                            #<%= d.view_cast.id.to_s %>
                                        <% end %>
                                    </td>
                                    <td class="hint">
                                		<% if d.intersection.present? %>
                                            <%= d.intersection.name %>
                                        <% end %>
                                        <% if d.sub_intersection.present? %>
                                                /
                                                <%= d.sub_intersection.name %>
                                        <% end %>
                                    </td>
                                    <td><div class="status-signal <%= d.status == 'draft' ? "status-red" : "status-green" %>"></div>
                                    </td>
                                    <td>
                                        <%= link_to truncate(d.headline, length: 45, ommission: ".."), (['article', 'compendium'].include?(d.template_page.name) ?  edit_write_site_story_path(@site, d, folder_id: d.folder_id) : edit_distribute_site_story_path(@site, d, folder_id: d.folder_id)), "data-turbolinks"=> false %>
                                    </td>
                                    <td>
                                        <% if d.byline.present? %>
                                            <%= d.byline.name %>
                                        <% end %>
                                    </td>
                                    <td class="hint"><%= d.published_at.nil? ? "" :  time_ago_in_words(d.published_at) %>
                                    </td>
                                    <td class="hint"><%= image_tag avatar_url(d.updator.email), width: "16px", height: "16px" %> <%= time_ago_in_words(d.updated_at) %>
                                    </td>
                                </tr>
                            <% end %>
                        </tbody>
                </table>
                <%= paginate @pages, theme: 'twitter-bootstrap-4', pagination_class: "pagination-sm" %>
            <% end %>
    </div>
    <div class="col-sm-4" style="padding-left: 6.25%; padding-right: 0px; padding-top: 70px;">

            <% if @pages.present? %>
                      <%= search_form_for @q, url: site_folder_stories_path(@site, @folder) do |f| %>
                          <%= f.label :english_headline_cont %>
                          <%= f.search_field :english_headline_or_headline_cont, :class => "form-control" %>
                          <br/>
                          <%= f.label :ref_category_intersection_id_eq, "Intersection" %>
                          <%= f.select :ref_category_intersection_id_eq, options_from_collection_for_select(@ref_intersections, :id, :name, @q.ref_category_intersection_id_eq), { :include_blank => true }, :class => "form-control" %>
                          <% if @ref_sub_intersections.present? %>
                              <br/>
                              <%= f.label :ref_category_sub_intersection_id_eq, "Trend" %>
                              <%= f.select :ref_category_sub_intersection_id_eq, options_from_collection_for_select(@ref_sub_intersections, :id, :name, @q.ref_category_sub_intersection_id_eq), { :include_blank => true }, :class => "form-control" %>
                          <% end %>
                          <br/>
                          <%= f.label :byline_id_eq, "Byline" %>
                          <%= f.select :byline_id_eq, options_from_collection_for_select(@bylines, :id, :name, @q.byline_id_eq), { :include_blank => true }, :class => "form-control" %>
                          <br/>
                          <%= f.submit "Search", class: "btn btn-sm btn-dark" %>
                          &nbsp;&nbsp;&nbsp;&nbsp;
                          |&nbsp;&nbsp;&nbsp;&nbsp;
                          <%= link_to "Reset", site_folder_stories_path(@site, @folder) %>
                      <% end %>
            <% end %>
    </div>

</div>