config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {registrations: 'user/registrations'} do
    get 'sign_out', to: 'devise/sessions#destroy'
  end

  resources :users do
      resources :user_emails, only: [:index, :create, :destroy]
      get '/user_emails/confirmation', to: "user_emails#confirmation", as: "email_confirmation"
  end

  namespace :api do
    namespace :v1 do
      resources :sites, only: [] do
        resources :folders do
          resources :pages, only: [:create, :update]
          resources :streams, only: [:create, :update]
          resources :template_cards, only: [:index, :show] do
            get "validate", on: :member
          end
          resources :datacasts, only: [:create, :update]
          resources :streams, only: [:create, :update]
          post "/streams/:id/publish", to: "streams#publish", as: :publish_stream
        end
        resources :verticals, only: [] do
          get "view_casts", on: :member
        end
      end

      # resources :folders, only: [] do
      #   resources :template_cards, only: [:index, :show] do
      #     get "validate", on: :member
      #   end
      #   resources :datacasts, only: [:create, :update]
      #   resources :streams, only: [:create, :update]
      #   post "/streams/:id/publish", to: "streams#publish", as: :publish_stream
      # end
      post "smartcrop", to: "utilities#smartcrop"
      get '/iframely', to: "utilities#iframely"
      get '/oembed', to: "utilities#oembed"
      resources :view_casts, only: [:show]
      resources :template_data, only: [:create]
    end
  end

  get ":site_id/apps", to: "template_apps#index", as: :apps_site
  get ":site_id/apps/d/:template_datum_id", to: "template_data#show", as: :site_template_datum
  get ":site_id/apps/d/:template_datum_id/:id", to: "template_fields#edit", as: :edit_site_template_datum_template_field

  resources :sites do
    post "fetch_new_data", on: :member
    #app store ---
    resources :template_apps, only: [:edit, :update]
    resources :site_template_apps, only: [:index, :destroy, :install] do
      post "invite", on: :member
      get "accept", on: :member
    end
    resources :template_data, only: [] do
      resources :template_fields do
        get "move_up", on: :member
        get "move_down", on: :member
      end
    end
    #app store ---

    resources :permissions do
      get "change_owner_role", on: :member
      put "change_role", on: :member
    end
    resources :permission_invites
    get "remove_favicon", "remove_logo", "integrations", on: :member
    resources :ref_categories do
      get 'landing_card', on: :member
      resources :feeds do
        post "force_fetch_feeds", on: :member
      end
      resources :feed_links do
        post "create_view_cast", on: :member
      end
      resources :site_vertical_navigations do
        put "move_up", "move_down", on: :member
      end
      put '/disable', to: "ref_categories#disable", on: :member
    end
    get "/sections", to: "ref_categories#sections", on: :member
    get "/intersections", to: "ref_categories#intersections", on: :member
    get "/sub_intersections", to: "ref_categories#sub_intersections", on: :member

    resources :folders do
      resources :stories, only: [:index]

      resources :view_casts
      resources :uploads, only: [:new, :create, :index]
    end
    resources :pages do
      put "remove_cover_image", on: :member
      get "distribute", on: :member
      get "ads", on: :member
      resources :ad_integrations, only: [:create, :destroy]
    end
    resources :stories, only: [:index] do
      get "edit/write", to: "stories#edit_write", on: :member
      get "edit/assemble", to: "stories#edit_assemble", on: :member
      get "edit/distribute", to: "stories#edit_distribute", on: :member
      get "edit/ads", to: "stories#edit_ads", on: :member
      post "import", to: "stories#import_story", on: :collection
    end
    resources :streams do
      post :publish, on: :member
      resources :stream_entities, only: [:create, :destroy] do
        put "move_up", "move_down", on: :member
      end
    end
    resources :page_streams, only: [:update]
    resources :images, only: [:index, :create, :show]
    resources :image_variations, only: [:create, :show] do
      post :download, on: :member
    end
  end

  scope :admin do
    resources "template_pages", only: [:index, :create, :update, :edit, :destroy]
  end


  root 'static_pages#index'
end

app/models/ref_category.rb
# == Schema Information
#
# Table name: ref_categories
#
#  id                          :integer          not null, primary key
#  site_id                     :integer
#  genre                       :string(255)
#  name                        :string(255)
#  stream_url                  :text
#  created_at                  :datetime         not null
#  updated_at                  :datetime         not null
#  stream_id                   :integer
#  is_disabled                 :boolean
#  created_by                  :integer
#  updated_by                  :integer
#  count                       :integer          default(0)
#  name_html                   :text
#  slug                        :string(255)
#  english_name                :string(255)
#  vertical_page_url           :text
#  description                 :text
#  keywords                    :text
#  show_by_publisher_in_header :boolean          default(TRUE)
#  g_a_tracking_id             :string
#

class RefCategory < ApplicationRecord
    #CONSTANTS
    #CUSTOM TABLES
    #GEMS
    before_validation :before_validation_set
    extend FriendlyId
    friendly_id :english_name, use: :slugged
    #CONCERNS
    include Propagatable
    include AssociableBySi
    #ASSOCIATIONS
    has_one :stream, foreign_key: 'id', primary_key: 'stream_id'
    has_many :navigations, class_name: "SiteVerticalNavigation", foreign_key: "ref_category_vertical_id", dependent: :destroy
    has_one :folder, foreign_key: 'ref_category_vertical_id'
    has_many :folders, foreign_key: 'ref_category_vertical_id'
    has_many :pages, foreign_key: 'ref_category_series_id'
    has_many :feeds, dependent: :destroy

    has_many :stories_with_intersection, foreign_key: "ref_category_intersection_id", class_name: "Page"
    has_many :stories_with_sub_intersection, foreign_key: "ref_category_sub_intersection_id", class_name: "Page"

    #ACCESSORS
    #VALIDATIONS
    validates :name, presence: true, uniqueness: {scope: [:site, :genre]}, length: { in: 3..15 }
    validates :genre, inclusion: {in: ["intersection", "sub intersection", "series"]}

    #CALLBACKS
    before_create :before_create_set

    after_create :after_create_set
    before_update :before_update_set
    after_destroy :update_site_verticals
    after_update :update_page_seo_content
    after_update :update_site_verticals
    #SCOPE
    #OTHER

    def should_generate_new_friendly_id?
        self.slug.nil? || english_name_changed?
    end

    def vertical_page
        self.pages.where(template_page_id: TemplatePage.where(name: "Homepage: Vertical").first.id).first
    end

    # def vertical_page_url
    #     "#{self.site.cdn_endpoint}/#{self.slug}.html"
    # end

    #TODO AMIT / AB2: I am temporarily changing is_autogenerated: to TRUE
    def view_casts
        if genre == "series"
            ViewCast.where(template_card_id: TemplateCard.where(name: "toStory").pluck(:id)).where(ref_category_vertical_id: self.id)
        elsif genre == "intersection"
            ViewCast.where(template_card_id: TemplateCard.where(name: "toStory").pluck(:id)).where(ref_category_intersection_id: self.id)
        else
            ViewCast.where(template_card_id: TemplateCard.where(name: "toStory").pluck(:id)).where(ref_category_sub_intersection_id: self.id)
        end
    end

    def cards_as_json
        view_casts = site.view_casts.select(:name, :id, :folder_id, :template_card_id, :datacast_identifier, :site_id).includes(:folder, :template_card).where.not(template_card_id: TemplateCard.where(name: ["toCoverImage", "toCoverStory", "Footer", "Header", "toParagraph"]).pluck(:id)).where.not(folder_id: site.folders.where(is_trash: true).pluck(:id)).order([updated_at: :desc, created_at: :desc])
        json_data = []

        view_casts.each do |d|
            obj = {}
            obj["folder_name"] = d.folder.name
            obj['template_card_name'] = d.template_card.name
            obj['template_card_id'] = d.template_card_id
            obj['id'] = d.id
            obj["datacast_identifier"] = d.datacast_identifier
            obj["name"] = d.name
            obj['iframe_url'] = d.template_card.index_html + "?view_cast_id=#{d.datacast_identifier}" + "&base_url= #{d.site.cdn_endpoint}"

            json_data << obj
        end

        json_data
    end

    def vertical_header_key
        "#{self.slug}/navigation.json"
    end

    def vertical_header_url
        "#{self.site.cdn_endpoint}/#{vertical_header_key}"
    end

    def update_site_verticals
        Thread.new do
            verticals_json = []
            self.site.verticals.each do |ver|
                next unless ver.vertical_page.present? and ver.vertical_page.is_published
                verticals_json << {"name": "#{ver.name}","url": "#{ver.vertical_page_url}","new_window": true, "name_html": "#{ver.name_html}", "show_by_publisher_in_header": ver.show_by_publisher_in_header }
            end
            key = "#{self.site.homepage_header_key}"
            encoded_file = Base64.encode64(verticals_json.to_json)
            content_type = "application/json"
            resp = Api::ProtoGraph::Utility.upload_to_cdn(encoded_file, key, content_type, self.site.cdn_bucket)
            Api::ProtoGraph::CloudFront.invalidate(self.site, ["/#{key}"], 1)
            ActiveRecord::Base.connection.close
        end
    end

    def update_page_seo_content
        if (["keywords", "description"] & self.saved_changes.transform_values(&:first).keys).length > 0
            self.vertical_page.update_columns(meta_description: description, meta_keywords: keywords)
        end
    end

    def before_validation_set
        self.english_name = self.name if self.site.is_english
    end

    class << self

        def find_or_create(genre, site_id, name, created_by, updated_by)
            rc = where(genre: genre, name: name).first
            if rc.blank?
                rc = create({genre: genre, name: name, site_id: site_id, created_by: created_by, updated_by: updated_by, english_name: name})
            end
            rc
        end

    end

    #PRIVATE
    private

    def before_create_set
        self.vertical_page_url = "#{self.site.cdn_endpoint}/#{self.slug}.html" if self.vertical_page_url.blank?
        true
    end

    def before_update_set
        self.is_disabled = true if self.count > 0
        self.english_name = ActionView::Base.full_sanitizer.sanitize(self.english_name)
        self.name_html = self.name if self.name_html.blank?
        true
    end

    def after_create_set
        s = Stream.create!({
            is_automated_stream: true,
            col_name: "RefCategory",
            col_id: self.id,
            title: self.name,
            description: "#{self.name} stream",
            site_id: self.site_id,
            limit: 50
        })

        self.update_columns(stream_url: "#{s.site.cdn_endpoint}/#{s.cdn_key}", stream_id: s.id)

        # Create a new page object
        if self.genre == "series"
            page = Page.create({
                site_id: self.site_id,
                headline: "#{self.name + " "*(50 - (self.name.length)) }",
                template_page_id: TemplatePage.where(name: 'Homepage: Vertical').first.id,
                ref_category_series_id: self.id,
                created_by: self.created_by,
                updated_by: self.updated_by,
                datacast_identifier: "",
                url: "#{vertical_page_url}",
                meta_description: "#{description}",
                meta_keywords: "#{keywords}"
            })
            page.push_json_to_s3
            #Update the site vertical json
            update_site_verticals
            key = self.vertical_header_key
            encoded_file = Base64.encode64({"Header"=>[], "Footer"=>[]}.to_json)
            content_type = "application/json"
            resp = Api::ProtoGraph::Utility.upload_to_cdn(encoded_file, key, content_type, self.site.cdn_bucket)
        end
    end

end

app/controllers/ref_categories_controller.rb
class RefCategoriesController < ApplicationController

  before_action :authenticate_user!
  before_action :sudo_role_can_add_site_categories, only: [:create]
  before_action :sudo_role_can_disable_site_categories, only: [:update]
  before_action :set_entity, only: [:edit, :update, :destroy, :disable, :landing_card]

  def edit
  end

  def sections
    @genre = "series"
    @data = @site.ref_categories.where(genre: "series").order(:name)
    @instance = RefCategory.new
    render :index
  end

  def intersections
    @is_admin = true
    @genre = "intersection"
    @data = @site.ref_categories.where(genre: "intersection").order(:name)
    @instance = RefCategory.new
    @is_admin = true
    render :index
  end

  def sub_intersections
    @is_admin = true
    @genre = "sub intersection"
    @data = @site.ref_categories.where(genre: "sub intersection").order(:name)
    @instance = RefCategory.new
    @is_admin = true
    render :index
  end

  def create
    @ref_category = RefCategory.new(entity_params)
    @ref_category.created_by = current_user.id
    @ref_category.updated_by = current_user.id
      if @ref_category.save
        @notice = 'Created successfully.'
        custom_redirect_to
      else
        case @ref_category.genre
        when 'series'
          redirect_to sections_site_path(@site), alert: @ref_category.errors.full_messages
        when 'intersection'
          redirect_to intersections_site_path(@site), alert: @ref_category.errors.full_messages
        when 'sub intersection'
          redirect_to sub_intersections_site_path(@site), alert: @ref_category.errors.full_messages
        end
      end
  end

  def update
    respond_to do |format|
      if @ref_category.update_attributes(entity_params)
        @notice = 'Updated successfully.'
        format.json { respond_with_bip(@ref_category) }
        format.html { custom_redirect_to }
      else
        format.json { respond_with_bip(@ref_category) }
        format.html { render :action => "edit" }
      end
    end
  end

  def disable
    @ref_category.update_attributes(is_disabled: true, updated_by: current_user.id)
    @notice = 'Ref category was successfully disabled.'
    custom_redirect_to
  end

  def destroy
    @genre = @ref_category.genre
    @ref_category.destroy
    respond_to do |format|
        case @genre
        when 'series'
          format.html { redirect_to sections_site_path(@site), notice: "Destroyed"}
        when 'intersection'
          format.html { redirect_to intersections_site_path(@site), notice: "Destroyed"}
        when 'sub intersection'
          format.html { redirect_to sub_intersections_site_path(@site), notice: "Destroyed"}
        end
    end
  end

  def custom_redirect_to
    case @ref_category.genre
    when 'series'
      redirect_to sections_site_path(@site)
    when 'intersection'
      redirect_to intersections_site_path(@site), notice: @notice
    when 'sub intersection'
      redirect_to sub_intersections_site_path(@site), notice: @notice
    end
  end

  def landing_card
    @page = @ref_category.vertical_page
    @view_cast = @page.landing_card
    if (Time.now - @view_cast.updated_at) > 5.minute and (@view_cast.is_invalidating)
        @view_cast.update_column(:is_invalidating, false)
    end
    @view_cast_seo_blockquote = @view_cast.seo_blockquote.to_s.split('`').join('\`')
  end

  private

    def set_entity
      @ref_category = RefCategory.friendly.find(params[:id])
    end

    def entity_params
      if params[:ref_category].present?
        params.require(:ref_category).permit(:site_id, :genre, :name, :english_name,:name_html, :show_by_publisher_in_header, :is_disabled, :created_by, :updated_by, :vertical_page_url, :description, :keywords)
      end
    end
end

app/views/ref_categories/_header.html.erb
<h1>Plan</h1>
<div class="protograph-page-tabs">
    <div class="<%= action_name == 'intersections' ? "single-tab active-tab" : "single-tab" %>">
        <%= link_to "Intersections", intersections_site_path(@site),"data-turbolinks" => "false" %>
    </div>
    <div class="<%= action_name == 'sub_intersections' ? "single-tab active-tab" : "single-tab" %>">
        <%= link_to "Trends", sub_intersections_site_path(@site),"data-turbolinks" => "false" %>
    </div>
    <div class="<%= action_name == 'sections' ? "single-tab active-tab" : "single-tab" %>">
        <%= link_to "Subsites", sections_site_path(@site),"data-turbolinks" => "false" %>
    </div>
</div>
<br/>

app/views/ref_categories/edit.html.erb
<div class="row">
  <div class="col-sm-13">
    <div style="margin-left: auto; margin-right: auto; width: 540px;">
      <%= simple_form_for [@site, @ref_category] do |f| %>
        <h4>
          <%=  @ref_category.name %>
        </h4>
        <%= f.hidden_field :site_id, value: @site.id %>
        <div class="form-inputs">
          <%= f.input :description, as: :text, label: "Description", hint: "Used for SEO." %>
          <%= f.input :keywords, as: :text, label: "Keywords", hint: "Used for SEO." %>
        </div>
        <div class="form-actions">
            <%= f.button :submit, value: "Update", class: "btn btn-sm btn-secondary" %>
        </div>
        <td class='hint'>
  <%# if action_name != "verticals" %>
      <%# unless ref_category.is_disabled %>
        <%# if ref_category.count > 0 %>
          <%#= link_to 'Disable', disable_site_ref_category_path(@site, ref_category), method: :put, data: { confirm: 'Are you sure?' } %>
        <%# else %>
          <%#= link_to 'x', site_ref_category_path(@site, ref_category), method: :delete, data: { confirm: 'Are you sure?' } %>
        <%# end %>
      <%# end %>
  <%# else %>
      <%# if ref_category.pages.count < 1 %>
        <%#= link_to 'x', site_ref_category_path(@site, ref_category), method: :delete, data: { confirm: 'Are you sure?' }, input_html: {"disabled": true} %>
      <%# else %>
        <%#= link_to 'x', "#", style: "color: #d3d3d3;","data-title" => "You cannot delete this vertical as it has associated pages", "data-toggle" => "tooltip", "data-placement" => "bottom" %>
      <%# end %>
  <%# end %>
</td>
      <% end %>
    </div>
  </div>
</div>

app/views/ref_categories/index.html.erb
<%= render partial: "ref_categories/header" %>
<div class="row">
  <div class="col-sm-13">
    <div style="margin-left: auto; margin-right: auto; width: 540px;" class='table-responsive'>
      <% if @data.first.blank? %>
        <div class="hint">No rows yet</div>
      <% else %>
        <table class="table table-bordered table-hover">
          <thead>
            <tr>
              <td>Name
              </td>
              <td>Stories
              </td>
              <td>Created
              </td>
              <td>Updated
              </td>
            </tr>
          </thead>
          <tbody>
            <% @data.each do |ref_category| %>
              <tr>
                <td>
                  <% if ref_category.is_disabled %>
                    <span class="proto-restrict-remove"><%= ref_category.name %></span>
                  <% else %>
                    <%= ref_category.name %>
                  <% end %>
                </td>
                <td>
                  <% if @genre == "intersection" %>
                      <%= ref_category.stories_with_intersection.count%>
                  <% elsif @genre == "sub intersection" %>
                      <%= ref_category.stories_with_sub_intersection.count%>
                  <% end %>
                </td>
                <td class="hint">
                  <%= image_tag avatar_url(ref_category.creator.email), class: "rounded" %> <%= time_ago_in_words ref_category.created_at %>
                </td>
                <td class="hint">
                  <%= image_tag avatar_url(ref_category.updator.email), class: "rounded" %> <%= time_ago_in_words ref_category.updated_at %>
                </td>
                <!-- <td> -->
                  <%#= link_to "Edit", (ref_category.genre == "series") ? distribute_site_page_path(@site, ref_category.vertical_page) :edit_site_ref_category_path(@site, ref_category) %>
                <!-- </td> -->
                <!-- <td>

                </td> -->
              </tr>
            <% end %>
          </tbody>
        </table>
      <% end %>
    </div>
  </div>
	<div class="col-sm-3">
    <% if action_name != "sections" %>
      <%= simple_form_for(@instance, url: site_ref_categories_path(@site), method: :post) do |f| %>
        <%= f.error_notification %>
        <%= f.hidden_field :genre, value: @genre %>
        <%= f.hidden_field :site_id, value: @site.id %>

        <div class="form-inputs">
            <%= f.input :name, required: true, minlength: 3 , maxlength: 15 %>
            <% unless @site.is_english %>
              <%= f.input :english_name, required: true, minlength: 3 , maxlength: 15, hint: "This is used for url management." %>
            <% end %>
        </div>
        <div class="form-actions">
            <%= f.button :submit, value: "Add", class: "btn btn-sm btn-secondary" %>
        </div>
      <% end %>
    <% else %>
        <%= simple_form_for(@instance, url: site_ref_categories_path(@site), method: :post) do |f| %>
        <%= f.error_notification %>
        <%= f.hidden_field :genre, value: "series" %>
        <%= f.hidden_field :site_id, value: @site.id %>

        <div class="form-inputs">
          <%= f.input :name, required: true, minlength: 3 , maxlength: 15, hint: "Choose carefully. Once set, you cannot change the name." %>
          <% unless @site.is_english %>
            <%= f.input :english_name, required: true, minlength: 3 , maxlength: 15, hint: "This is used for url management." %>
          <% end %>
          <%= f.input :name_html, as: :text, label: "Brand the subsite", hint: "Use HTML (span tag) to add CSS. Note, the length of the series cannot be more than 15 characters.", required: true, minlength: 3 , maxlength: 50 %>
        </div>
        <div class="form-actions">
            <%= f.button :submit, value: "Add a section", class: "btn btn-sm btn-secondary" %>
        </div>
        <% end %>
    <% end %>
	</div>
</div>